# Generated by Django 3.2.9 on 2021-12-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='cat1', max_length=30, verbose_name='category'),
        ),
    ]
