# Generated by Django 4.0 on 2022-01-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='address'),
        ),
    ]
