# Generated by Django 4.0 on 2022-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_item_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='main_img',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='main_img'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='status'),
        ),
    ]
